/* eslint-disable prettier/prettier */
import { StyleSheet } from 'react-native';
import { COLORS } from '../../../../../../constants';

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  barTopContainer: {
    width: '100%',
  },
  scrollContainer: {
    flexGrow: 1,
    marginTop: 55, // Ajuste conforme a altura do BarTop2 para evitar sobreposição
  },
  title: {
    fontSize: 20,
    fontWeight: '900',
    color: COLORS.black,
    paddingLeft: 20,
    backgroundColor: COLORS.primary,
  },
  contentContainer: {
    flexDirection: 'row',
    paddingHorizontal: 20,
    paddingTop: 10,
    backgroundColor: COLORS.primary,
  },
  leftContainer: {
    flex: 1,
    alignItems: 'center',
    marginLeft: -80,
  },
  rightContainer: {
    flex: 1,
    justifyContent: 'space-between',
    marginLeft: -80,
    paddingLeft: 20,
  },
  imageContainer: {
    alignItems: 'center',
    marginBottom: 20,
  },
  imageButton: {
    width: 100,
    height: 100,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageLabel: {
    marginTop: 10,
    color: COLORS.black,
    fontWeight: '500',
    textAlign: "center",
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 20,
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    paddingBottom: 5,
  },
  input: {
    flex: 1,
    color: COLORS.black,
    marginBottom: -10,
  },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 2,
    paddingHorizontal: 15,
    backgroundColor: COLORS.white,
    marginBottom: 5,
    borderRadius: 10,
  },
  controlInput: {
    marginHorizontal: 5,
    justifyContent: 'center',
    marginRight: -5,
  },
  controlButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  controlButton: {
    width: 25,
    height: 25,
    borderRadius: 5,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlValue: {
    fontWeight: 'bold',
    marginHorizontal: 10,
  },
  productDetailsContainer: {
    backgroundColor: COLORS.white,
    padding: 20,
    marginHorizontal: 20,
    marginVertical: 10,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: 15,
  },
  productNameInput: {
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    marginBottom: 20,
    paddingVertical: 5,
    color: COLORS.black,
  },
  serviceDescriptionInput: {
    height: 80,
    borderRadius: 5,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: 10,
    paddingVertical: 10,
    textAlignVertical: 'top',
    color: COLORS.black,
  },
  categoryContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 20,
    marginHorizontal: 20,
    marginTop: 15,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  categoryTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: 10,
  },
  categoryInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: COLORS.black,
  },
  categoryPicker: {
    flex: 1,
    color: COLORS.lightGray,
    paddingVertical: 10,
    paddingRight: 10,
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    width: '50%',
  },
  addButton: {
    width: 60,
    height: 40,
    backgroundColor: COLORS.primary, 
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginLeft: 20,
  },
  containerProductValues: {
    marginVertical: 15,
  },
  registerButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: 25,
    paddingHorizontal: 20,
    marginHorizontal: 20,
    marginTop: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 40,
    flexDirection: 'row',
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
    marginLeft: 10,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    width:'90%'
  },
  modalText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: COLORS.black,
    textAlign: 'center',
  },
  modalButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 25,
    paddingHorizontal: 30,
    borderRadius: 5,
    marginTop: 20,
    width: '100%',
    alignItems: 'center',
  },
  modalButtonRetorno: {
    backgroundColor: COLORS.white,
    paddingVertical: 25,
    paddingHorizontal: 30,
    borderRadius: 5,
    marginTop: 10,
    width: '100%',
    alignItems: 'center',
    elevation:1
  },
  modalButtonText: {
    fontSize: 16,
    color: COLORS.black,
  },
});

export default styles;
