/* eslint-disable prettier/prettier */
import { StyleSheet, Dimensions } from 'react-native';
import { COLORS } from '../../../../../../constants';

const { width, height } = Dimensions.get('window');

const styles = StyleSheet.create({
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.background,
  },
  barTopContainer: {
    width: '100%',
  },
  scrollContainer: {
    flexGrow: 1,
    marginTop: height * 0.07, // Ajuste conforme a altura do BarTop2
  },
  title: {
    fontSize: width * 0.05,
    fontWeight: '900',
    color: COLORS.black,
    paddingLeft: width * 0.05,
    backgroundColor: COLORS.primary,
  },
  contentContainer: {
    flexDirection: 'row',
    paddingHorizontal: width * 0.05,
    paddingTop: height * 0.01,
    backgroundColor: COLORS.primary,
  },
  leftContainer: {
    flex: 1,
    alignItems: 'center',
    marginLeft: width * -0.2,
  },
  rightContainer: {
    flex: 1,
    justifyContent: 'space-between',
    marginLeft: width * -0.2,
    paddingLeft: width * 0.05,
  },
  imageContainer: {
    alignItems: 'center',
    marginBottom: height * 0.02,
  },
  imageButton: {
    width: width * 0.25,
    height: width * 0.25,
    borderRadius: 10,
    backgroundColor: COLORS.white,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageLabel: {
    marginTop: height * 0.01,
    color: COLORS.black,
    fontWeight: '500',
    textAlign: "center",
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: height * 0.02,
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    paddingBottom: height * 0.005,
  },
  input: {
    flex: 1,
    color: COLORS.black,
    marginBottom: height * -0.01,
  },
  controlRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: height * 0.002,
    paddingHorizontal: width * 0.05,
    backgroundColor: COLORS.white,
    marginBottom: height * 0.01,
    borderRadius: 10,
    width: '100%',
  },
  controlInput: {
    marginHorizontal: width * 0.012,
    justifyContent: 'center',
    marginRight: width * -0.012,
  },
  controlButtons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  controlButton: {
    width: width * 0.06,
    height: width * 0.06,
    borderRadius: 5,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
  },
  controlValue: {
    fontWeight: 'bold',
    marginHorizontal: width * 0.025,
  },
  productDetailsContainer: {
    backgroundColor: COLORS.white,
    padding: width * 0.05,
    marginHorizontal: width * 0.05,
    marginVertical: height * 0.01,
    borderRadius: 10,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  sectionTitle: {
    fontSize: width * 0.045,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: height * 0.015,
  },
  productNameInput: {
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    marginBottom: height * 0.02,
    paddingVertical: height * 0.005,
    color: COLORS.black,
  },
  serviceDescriptionInput: {
    height: height * 0.1,
    borderRadius: 5,
    backgroundColor: '#F5F5F5',
    paddingHorizontal: width * 0.025,
    paddingVertical: height * 0.012,
    textAlignVertical: 'top',
    color: COLORS.black,
  },
  categoryContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: width * 0.05,
    marginHorizontal: width * 0.05,
    marginTop: height * 0.015,
    elevation: 2,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
  },
  categoryTitle: {
    fontSize: width * 0.04,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: height * 0.012,
  },
  categoryInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderColor: COLORS.black,
  },
  categoryPicker: {
    flex: 1,
    color: COLORS.lightGray,
    paddingVertical: height * 0.012,
    paddingRight: width * 0.025,
    borderBottomWidth: 1,
    borderColor: COLORS.black,
    width: '50%',
  },
  addButton: {
    width: width * 0.15,
    height: height * 0.05,
    backgroundColor: COLORS.primary,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 5,
    marginLeft: width * 0.05,
  },
  containerProductValues: {
    marginVertical: height * 0.015,
  },
  registerButton: {
    backgroundColor: COLORS.primary,
    borderRadius: 8,
    paddingVertical: height * 0.03,
    paddingHorizontal: width * 0.05,
    marginHorizontal: width * 0.05,
    marginTop: height * 0.012,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: height * 0.05,
    flexDirection: 'row',
  },
  buttonText: {
    fontSize: width * 0.04,
    fontWeight: 'bold',
    color: COLORS.black,
    marginLeft: width * 0.025,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContainer: {
    backgroundColor: COLORS.white,
    borderRadius: 10,
    padding: width * 0.05,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.2,
    shadowRadius: 5,
    elevation: 5,
    width: '90%',
  },
  modalText: {
    fontSize: width * 0.05,
    fontWeight: 'bold',
    color: COLORS.black,
    textAlign: 'center',
  },
  modalButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: height * 0.03,
    paddingHorizontal: width * 0.075,
    borderRadius: 5,
    marginTop: height * 0.025,
    width: '100%',
    alignItems: 'center',
  },
  modalButtonRetorno: {
    backgroundColor: COLORS.white,
    paddingVertical: height * 0.03,
    paddingHorizontal: width * 0.075,
    borderRadius: 5,
    marginTop: height * 0.012,
    width: '100%',
    alignItems: 'center',
    elevation: 1,
  },
  modalButtonText: {
    fontSize: width * 0.04,
    color: COLORS.black,
  },
});

export default styles;
