/* eslint-disable prettier/prettier */
import { StyleSheet } from "react-native";
import { COLORS } from "../../../../constants";

const styles = StyleSheet.create({
    container: {
      alignItems: 'center',
      position: 'absolute',
      right: 20,
      bottom: 100,
    },
    button: {
      width: 60,
      height: 60,
      borderRadius: 30,
      backgroundColor: COLORS.primary,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'flex-end',
    },
    modalContent: {
      width: '100%',
      backgroundColor: '#fff',
      borderTopLeftRadius: 10,
      borderTopRightRadius: 10,
      padding: 20,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    modalButton: {
      width: '100%',
      padding: 15,
      borderRadius: 5,
      backgroundColor: '#fff',
      alignItems: 'center',
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      paddingVertical: 35,
    },
    modalButton2: {
      width: '100%',
      padding: 15,
      borderRadius: 5,
      backgroundColor: '#fff',
      alignItems: 'center',
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 1,
      flexDirection: 'row',
      justifyContent: 'center',
      paddingVertical: 35,
      borderWidth: 1,
    },
    modalText: {
      fontSize: 18,
      marginLeft: 5,
    },
    yellowButton: {
      backgroundColor: COLORS.primary,
    },
    blackText: {
      color: COLORS.black,
    },
  
// Estilos do Segundo Modal
secondModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  secondModalContent: {
    width: '80%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  secondModalHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  secondModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.black,
    width: '90%',
    justifyContent: 'center',
    textAlign: 'center',
  },
  secondModalButton: {
    width: '100%',
    padding: 15,
    borderRadius: 5,
    backgroundColor: COLORS.primary,
    alignItems: 'center',
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 25,
  },
  secondModalText: {
    fontSize: 16,
    color: COLORS.black,
    marginLeft: 5,
  },

    // Estilos do Terceiro Modal - Nova Venda
    thirdModalOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.5)',
      justifyContent: 'center',
      alignItems: 'center',
    },
    thirdModalContent: {
      width: '90%',
      backgroundColor: '#fff',
      borderRadius: 10,
      padding: 20,
      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 5,
    },
    thirdModalHeader: {
      width: '100%',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 20,
    },
    thirdModalTitle: {
      fontSize: 18,
      fontWeight: 'bold',
      color: COLORS.green,

    },
    thirdModalSubtitle: {
      fontSize: 13,
      marginLeft: 10,
    },
    thirdModalSubtitle2: {
        fontSize: 16,
        marginBottom: 10,
        marginLeft: 10,
        color: COLORS.black,
      },
    thirdModalButton: {
      width: '100%',
      padding: 15,
      borderRadius: 5,
      backgroundColor: '#fff',
      alignItems: 'center',
      marginBottom: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
      elevation: 1,
      justifyContent: 'center',
      paddingVertical: 25,
    },
    thirdModalButton2: {
        width: '100%',
        padding: 15,
        borderRadius: 5,
        backgroundColor: '#fff',
        alignItems: 'center',
        marginBottom: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 1,
        justifyContent: 'center',
        flexDirection: 'row',
        paddingVertical: 25,
      },
    containerAvulsa:{
        flexDirection: 'row',
    },
    thirdModalText: {
      fontSize: 16,
      marginLeft: 5,
      color: COLORS.black,
    },
      // Estilos do Quarto Modal - Cadastrar Produtos ou Serviços
  fourthModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  fourthModalContent: {
    width: '90%',
    backgroundColor: '#fff',
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 5,
  },
  fourthModalHeader: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  fourthModalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginLeft: 75,
    color: COLORS.black,
  },
  fourthModalButton: {
    width: '100%',
    padding: 15,
    borderRadius: 5,
    backgroundColor: '#fff',
    alignItems: 'center',
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 1,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingVertical: 30,
  },
  fourthModalText: {
    fontSize: 16,
    color: COLORS.black,
  },
  });

  export default styles;