copy "D:\Celere\app\CelereApp\docs\ApeToolsGeneratedAssets\bundle\android\drawable-mdpi\icon.png" "D:\Celere\app\CelereApp\android\app\src\main\res\mipmap-mdpi\ic_launcher.png"
copy "D:\Celere\app\CelereApp\docs\ApeToolsGeneratedAssets\bundle\android\drawable-hdpi\icon.png" "D:\Celere\app\CelereApp\android\app\src\main\res\mipmap-hdpi\ic_launcher.png"
copy "D:\Celere\app\CelereApp\docs\ApeToolsGeneratedAssets\bundle\android\drawable-xhdpi\icon.png" "D:\Celere\app\CelereApp\android\app\src\main\res\mipmap-xhdpi\ic_launcher.png"
copy "D:\Celere\app\CelereApp\docs\ApeToolsGeneratedAssets\bundle\android\drawable-xxhdpi\icon.png" "D:\Celere\app\CelereApp\android\app\src\main\res\mipmap-xxhdpi\ic_launcher.png"
copy "D:\Celere\app\CelereApp\docs\ApeToolsGeneratedAssets\bundle\android\drawable-xxxhdpi\icon.png" "D:\Celere\app\CelereApp\android\app\src\main\res\mipmap-xxxhdpi\ic_launcher.png"
