/* eslint-disable prettier/prettier */
import { StyleSheet } from 'react-native';
import { COLORS } from '../../../../../../../constants';

const styles = StyleSheet.create({
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Fundo escurecido
  },
  modalContent: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    height: "100%",
  },
  modalContentLiquidate: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalContent2: {
    backgroundColor: COLORS.white,
    marginHorizontal: 20,
    padding: 20,
    borderRadius: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
    height: "40%",
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',

  },
  modalTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.black,
  },
  modalClose: {
    fontSize: 20,
    color: COLORS.black,
    marginTop:-20,
  },
  containerTitle:{
    flexDirection: 'row',
    marginBottom: -5,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 5,
    color: COLORS.black,
  },
  sectionTitleRed: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    color: COLORS.red,
  },
  sectionTitleGreen: {
    fontSize: 14,
    fontWeight: 'bold',
    marginBottom: 10,
    color: COLORS.green,
  },
  productList: {
    marginBottom: 10,
  },
  productItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 5,
  },
  productInfo: {
    marginLeft: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',

  },
  productNome:{
    width: '50%',
    color: COLORS.black

  },
  productImage: {
    width: 50,
    height: 50,
    borderRadius: 5,
    marginRight: 10, // Espaço entre a imagem e as informações do produto
},

  productQuantidade:{
    color: COLORS.black,
  },
  totalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingVertical: 10,
    borderTopWidth: 1,
    borderColor: COLORS.lightGray,
  },
  totalLabel: {
    fontSize: 16,
    color: COLORS.black,
  },
  totalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
  },
  input: {
    height: 40,
    borderColor: 'gray',
    borderRadius: 8,
    paddingHorizontal: 10,
    marginBottom: 10,
    borderBottomWidth:1,
  },
  newTotalContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 20,
  },
  newTotalLabel: {
    fontSize: 16,
    color: COLORS.black,
  },
  newTotalValue: {
    fontSize: 16,
    fontWeight: 'bold',
    color: COLORS.black,
  },
  partialButton: {
    backgroundColor: COLORS.white,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    borderColor: COLORS.black,
    borderWidth: 1,
    marginBottom: 10,
    paddingVertical: 20,
  },
  totalButton: {
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 10,
    paddingVertical: 20,
  },
  cancelButtonModal: {
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 10,
    paddingVertical: 20,
  },
  reminderButton: {
    backgroundColor: COLORS.lightGray3,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 10,
    elevation: 1,
    paddingVertical: 20,
  },
  reciboButton: {
    backgroundColor: COLORS.white,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 10,
    elevation: 1,
    paddingVertical: 20,
  },
  postponeButton: {
    backgroundColor: COLORS.lightGray3,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginBottom: 10,
    elevation:1,
    paddingVertical: 20,
  },
  deleteButton: {
    backgroundColor: COLORS.white,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    elevation:1,
    paddingVertical: 20,
  },
  backButton: {
    backgroundColor: COLORS.white,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    elevation:1,
    paddingVertical: 20,
  },
  buttonText: {
    marginLeft: 10,
    fontWeight: 'bold',
    color: COLORS.black,
  },
  datePickerContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.lightGray,
  },
  dateLabel: {
    fontSize: 16,
    color: COLORS.gray,
  },
  confirmButton: {
    backgroundColor: COLORS.primary,
    padding: 12,
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    marginTop: 20,
  },
  modalContainer3: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)', // Fundo escurecido para o modal
  },
  modalContent3: {
    backgroundColor: COLORS.white,
    padding: 20,
    borderRadius: 10,
    width: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  modalTitle3: {
    fontSize: 18,
    fontWeight: 'bold',
    color: COLORS.black,
    marginBottom: 10,
  },
  modalSubtitle3: {
    fontSize: 14,
    color: COLORS.black,
    marginBottom: 20,
    textAlign: 'center',
  },
  confirmationButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  cancelButton: {
    backgroundColor: COLORS.white,
    padding: 10,
    flex: 1,
    alignItems: 'center',
    marginRight: 10,
  },
  confirmButton3: {
    backgroundColor: COLORS.primary,
    padding: 10,
    borderRadius: 5,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
  },
  buttonText3: {
    fontWeight: 'bold',
    color: COLORS.black,
    marginLeft: 5,
  },
    // Estilos para o Quarto Modal de Sucesso
    modalContainer4: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: 'rgba(0, 0, 0, 0.5)', // Fundo escurecido
    },
    modalContent4: {
      backgroundColor: '#fff',
      width: 300,
      padding: 20,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 10,
    },
    successText: {
      fontSize: 22,
      fontWeight: 'bold',
      color: 'black',
      marginTop: 10,
      marginBottom: 20,
      textAlign: 'center',
    },
    successButton: {
      backgroundColor: COLORS.primary,
      borderRadius: 5,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      paddingVertical:22,
      paddingHorizontal:100,
    },
    buttonText4: {
      fontSize: 16,
      color: 'black',
      marginLeft: 8,
    },
});

export default styles;